### ISSUE TITLE
refactor: ビルドスクリプトのTypeScript化

### ISSUE THREAD

**Issue by kyonenya** [kyonenya/kyonenya.github.io#55]
- [ ] `ts-node`を導入
  - ts-node-devとどちらがいいか
- [ ] `Post`オブジェクトの型を参照してタグ一覧のサイトマップ生成をやりたい
- [ ] csl-jsonの型を参照して業績リスト生成をやりたい

## ついでに

- [ ] PostのDateは+09:00つけとく
- 開発時にjsonに書いておいたlastModとかを参照して事前ビルドする？
  - 事前ビルドでもデータとスクリプトを分けておく
  - ハードコーディングはせず、distにのみハードコーディングされる

**Comment by kyonenya** [comment]
凍結。sitemapモジュールがts-node下だとwasmを参照していて、それがplay.jsで動かないため。

```
ReferenceError: WebAssembly is not defined
    at AsyncFunction.wasmSync [as sync] (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-consumer/lib/wasm.js:67:24)
    at new BasicSourceMapConsumer (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-consumer/lib/source-map-consumer.js:248:20)
    at _factory (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-consumer/lib/source-map-consumer.js:1223:7)
    at new SourceMapConsumer (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-consumer/lib/source-map-consumer.js:19:12)
    at mapSourcePosition (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-support/source-map-support.js:273:14)
    at wrapCallSite (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-support/source-map-support.js:461:20)
    at Function.prepareStackTrace (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-support/source-map-support.js:541:41)
    at maybeOverridePrepareStackTrace (internal/errors.js:81:29)
    at prepareStackTrace (internal/errors.js:60:5)
    at getErrorSource (/private/var/mobile/Containers/Shared/AppGroup/63072C22-D642-49C0-A35C-F51989ED4E30/File Provider Storage/Repositories/kyonenya.github.io/node_modules/@cspotcode/source-map-support/source-map-support.js:551:64)
```
